server.port: 7001
spring.data.mongodb:
   host: localhost
   port: 27017
   database: product-db

spring.mongodb.embedded.version: 4.4.9

logging.level:
   root: DEBUG
   org.springframework.data.mongodb.core.MongoTemplate: DEBUG

management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"
---
spring.profiles: docker
server.port: 8080
spring.data.mongodb.host: mongodb