server.port: 7002
server.error.include-message: always

spring.jpa.hibernate.ddl-auto: update

spring.datasource:
   url: jdbc:mysql://localhost/review-db
   username: user
   password: pwd

logging.level:
   root: INFO
   org.hibernate.SQL: DEBUG
   org.hibernate.type.descriptor.sql.BasicBinder: TRACE
   
spring.datasource.hikari.initializationFailTimeout: 60000

---
spring.profiles: docker
server.port: 8080

spring.datasource.url: jdbc:mysql://mysql/review-db
